name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          apk add --no-cache git make bash gcc musl-dev golangci-lint

      - name: Run CI via Makefile
        run: make ci
